"""empty message

Revision ID: 1d335047cd81
Revises: None
Create Date: 2016-06-27 18:23:15.716224

"""

# revision identifiers, used by Alembic.
revision = '1d335047cd81'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('link_clicked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'link_clicked')
    ### end Alembic commands ###
