"""empty message

Revision ID: 5c94e07d7cb5
Revises: 63d0f82ee0d2
Create Date: 2016-06-24 18:52:41.682321

"""

# revision identifiers, used by Alembic.
revision = '5c94e07d7cb5'
down_revision = '63d0f82ee0d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_authenticated')
    op.drop_column('user', 'confirmed_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
