"""empty message

Revision ID: 63d0f82ee0d2
Revises: c97a1b1d14c2
Create Date: 2016-06-24 18:46:00.478716

"""

# revision identifiers, used by Alembic.
revision = '63d0f82ee0d2'
down_revision = 'c97a1b1d14c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_active')
    ### end Alembic commands ###
