"""empty message

Revision ID: c06a15c72c64
Revises: None
Create Date: 2016-06-21 15:27:49.764065

"""

# revision identifiers, used by Alembic.
revision = 'c06a15c72c64'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timestamp')
    ### end Alembic commands ###
