"""empty message

Revision ID: c97a1b1d14c2
Revises: 4d5fd29c853c
Create Date: 2016-06-24 18:25:44.582817

"""

# revision identifiers, used by Alembic.
revision = 'c97a1b1d14c2'
down_revision = '4d5fd29c853c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_authenticated')
    ### end Alembic commands ###
