"""empty message

Revision ID: dedc5c4e326c
Revises: c06a15c72c64
Create Date: 2016-06-24 17:25:52.271329

"""

# revision identifiers, used by Alembic.
revision = 'dedc5c4e326c'
down_revision = 'c06a15c72c64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url')
    ### end Alembic commands ###
